export const dom = {
	skills: document.querySelector(".skills"),
	svgSkillTrees: document.querySelectorAll(".skill-tree"),
	svgSkillLines: document.querySelectorAll(".skill-lines__line"),
	skillTreeWrapper: document.querySelector(".skills__tree-wrapper"),
	skillIconsWrapper: document.querySelector(".skills__icons-wrapper"),
	skillIcons: document.querySelectorAll(".icons__skill-icon"),
	skillTreeName: document.querySelector(".tree-header__skill-tree-name"),
	skillTreeRace: document.querySelector(".skill-tree-race"),
	treeMaxActivePerks: document.querySelector(".tree-header__max-active-perks"),
	treeSkillLevel: document.querySelector(".tree-header__skill-level"),
	treeActivePerks: document.querySelector(".tree-header__active-perks"),
	iconNames: document.querySelectorAll("[data-icon-name]"),
	skillIconsPerksNumber: document.querySelectorAll("[data-chosen-perks]"),
	currentPerkRank: document.querySelectorAll(".perk-rank__rank"),
	perkInfo: document.querySelector(".perk-info"),
	perkName: document.querySelector(".perk-info__perk-name"),
	perkDescription: document.querySelector(".perk-info__perk-description"),
	perkInfoNextRank: document.querySelector(".perk-info__next-rank"),
	perkInfoNextRankDes: document.querySelector(".perk-info__next-rank-description"),
	perkInfoPerkSkill: document.querySelector(".perk-info__perk-skill"),
	perkInfoNextSkill: document.querySelector(".perk-info__next-skill"),
	clearTree: document.querySelector(".skills-header__clear-button--tree"),
	clearAllPerks: document.querySelector(".skills-header__clear-button--all"),
	skillsButton: document.querySelector(".category-button--skills"),
	boonsButton: document.querySelector(".category-button--boons"),
	overlay: document.querySelector("#overlay"),
	menuButton: document.querySelector(".main-buttons__menu"),
	characterButton: document.querySelector(".main-buttons__character"),
	saveCharacter: document.querySelector(".save-character"),
	characterName: document.querySelector("#character-name"),
	races: document.querySelector("#races"),
	warning: document.querySelector(".warning"),
	menu: document.querySelector(".menu"),
	createCharacter: document.querySelector(".create-character"),
	closeMenu: document.querySelector(".close-button"),
	openItems: document.querySelectorAll("[data-open-items]"),
	closeModal: document.querySelectorAll("[data-close-modal]"),
	currentName: document.querySelector(".current-character__name"),
	currentRace: document.querySelector(".current-character__race"),
	currentLevel: document.querySelector(".current-character__level"),
	menuOptions: document.querySelector(".menu-options"),
	header: document.querySelector("header"),
	main: document.querySelector("main"),
	showcase: document.querySelector(".showcase"),
	H1: document.querySelector("header h1"),
	typeButtons: document.querySelectorAll(".menu-options > div > div > button"),
	categoryContainers: document.querySelectorAll(".menu-options>div"),
	typeContainers: document.querySelectorAll(".menu-options > div > div"),
	cardsList: document.querySelector(".items-window__cards-list"),
	itemWindowHeader: document.querySelector(".items-window__title"),
	itemsTemplate: document.querySelector("#items-window-template"),
	sortByOtherName: document.querySelector(".items-window__sort-button--by-other span:first-child"),
	closeItemsButton: document.querySelector(".items-window__items .close-window"),
	itemsWindow: document.querySelector(".items-window"),
	selectedSortingBtns: document.querySelectorAll("[data-sorting-selected]"),
	sortByName: document.querySelector(".items-window__sort-button--by-name"),
	sortingDirection: document.querySelectorAll(".sorting-direction"),
	filterWindow: document.querySelector(".filter-window"),
	filterButton: document.querySelector(".items-window__filter-button"),
	checkboxes: document.querySelectorAll(".filter-window input"),
	sortByWeight: document.querySelector(".items-window__sort-button--by-weight"),
	sortByOther: document.querySelector(".items-window__sort-button--by-other"),
	sortButtons: document.querySelectorAll(".items-window__sort-button--by-name, .items-window__sort-button--by-weight, .items-window__sort-button--by-other"),
	chooseHandContainer: document.querySelector(".equip-options-window"),
	equippedCards: document.querySelector(".equipped-items"),
	itemsWindowItems: document.querySelector(".items-window__items"),
	fieldsetWrapper: document.querySelector(".filter-window__fieldset-wrapper"),
	closeFilter: document.querySelector(".filter-window .close-window"),
	cardsContainer: document.querySelector(".items-window__cards"),
	equippedCardsWrapper: document.querySelector(".equipped-items__wrapper"),
	itemsWrapper: document.querySelector(".items-window__wrapper"),
	biggerIMGContainer: document.querySelector(".items-window__bigger-img"),
	resistances: document.querySelectorAll("[data-resistances]"),
	characterSkills: document.querySelector(".info-win__character-skills-section"),
	template: document.querySelector("#character-skills-template"),
	searchField: document.querySelector(".items-window__search"),
	clearSearchButton: document.querySelector(".items-window__clear-search"),
	buildInfoTabPanel: document.querySelector(".info-win-tabs"),
	buildInfoTabs: document.querySelectorAll(".info-win-tabs__tab"),
	infoWindowsWrapper: document.querySelector(".info-win__wrapper"),
	infoWindows: document.querySelectorAll(".info-win__wrapper > section"),
	dlPassEff: document.querySelector(".passive-effects__dl"),
	passEffTemp: document.querySelector("#passive-effects-template"),
	passEffNothing: document.querySelector(".info-win__passive-effects-section .nothing-there-yet"),
	boons: document.querySelector(".boons"),
	boonsOptions: document.querySelector(".boons__options"),
	standingStones: document.querySelector(".boons__fieldset:first-child"),
	standingStonesLabels: document.querySelectorAll(".boons__fieldset:first-child label"),
	standingStonesInputs: document.querySelectorAll(".boons__fieldset:first-child input"),
	blessings: document.querySelector(".boons__fieldset:last-child"),
	blessingsLabels: document.querySelectorAll(".boons__fieldset:last-child label"),
	blessingsInputs: document.querySelectorAll(".boons__fieldset:last-child input"),
	par: document.querySelector(".boons__p"),
	fieldsetDivs: document.querySelectorAll(".boons__options fieldset div"),
	showcaseSlotWrapper: document.querySelector(".showcase__slot-wrapper"),
	unequipMiniatureContainer: document.querySelector(".showcase__unequip-item-wrapper"),
	unequipMiniatureName: document.querySelector(".unequip-item-from-showcase span"),
	unequipMiniatureModal: document.querySelector(".unequip-item-from-showcase"),
	unequipItemFromMenu: document.querySelector(".unequip-item-from-menu"),
	unequipItemFromMenuBtns: document.querySelectorAll(".unequip-item-from-menu button"),
	unequipItemFromMenuName: document.querySelector(".unequip-item-from-menu span"),
	selectHand: document.querySelector(".choose-hand"),
	itemReplacement: document.querySelector(".item-replacement"),
	sameItem: document.querySelector(".same-item"),
	sameItemButton: document.querySelector(".same-item__button"),
	itemReplacementFirstItem: document.querySelector(".item-replacement__first-item"),
	itemReplacementUnequipFirst: document.querySelector(".item-replacement__unequip-first"),
	itemReplacementUnequipSecond: document.querySelector(".item-replacement__unequip-second"),
	itemReplacementUnequipBody: document.querySelector(".item-replacement__unequip-body"),
	itemReplacementUnequipHead: document.querySelector(".item-replacement__unequip-head"),
	itemReplacementUnequipBoth: document.querySelector(".item-replacement__unequip-both"),
	placeForCards: document.querySelector(".info-win__item-info-section"),
	card: document.querySelector("#item-info-template"),
	details: document.querySelector("#item-details-template"),
	menuInventoryButton: document.querySelector(".items-window__equipped-button"),
	closeMenuInventory: document.querySelector(".equipped-items .close-window"),
	unarmedDamageDom: document.querySelector("[data-unarmed-damage]"),
};