export const isDesktop = checkForDesktop();
function checkForDesktop() {
	const ua = navigator.userAgent.toLowerCase();
	if (/mobile|iphone|ipod|android.*mobile|windows phone/.test(ua)) return false;
	if (/android/.test(ua) && !/mobile/.test(ua)) return false;
	if (/ipad|tablet/.test(ua)) return false;
	return true;
}
export const raceSkills = {
	Argonian: {
		Alchemy: 15,
		Alteration: 20,
		Archery: 15,
		Block: 15,
		Conjuration: 15,
		Destruction: 15,
		Enchanting: 15,
		"Heavy Armor": 15,
		Illusion: 15,
		"Light Armor": 20,
		Lockpicking: 25,
		"One-Handed": 15,
		Pickpocket: 20,
		Restoration: 20,
		Smithing: 15,
		Sneak: 20,
		Speech: 15,
		"Two-Handed": 15,
	},
	Breton: {
		Alchemy: 20,
		Alteration: 20,
		Archery: 15,
		Block: 15,
		Conjuration: 25,
		Destruction: 15,
		Enchanting: 15,
		"Heavy Armor": 15,
		Illusion: 20,
		"Light Armor": 15,
		Lockpicking: 15,
		"One-Handed": 15,
		Pickpocket: 15,
		Restoration: 20,
		Smithing: 15,
		Sneak: 15,
		Speech: 20,
		"Two-Handed": 20,
	},
	"Dark Elf": {
		Alchemy: 20,
		Alteration: 20,
		Archery: 15,
		Block: 15,
		Conjuration: 15,
		Destruction: 25,
		Enchanting: 15,
		"Heavy Armor": 15,
		Illusion: 20,
		"Light Armor": 20,
		Lockpicking: 15,
		"One-Handed": 15,
		Pickpocket: 15,
		Restoration: 15,
		Smithing: 15,
		Sneak: 20,
		Speech: 15,
		"Two-Handed": 15,
	},
	"High Elf": {
		Alchemy: 15,
		Alteration: 20,
		Archery: 15,
		Block: 15,
		Conjuration: 20,
		Destruction: 20,
		Enchanting: 20,
		"Heavy Armor": 15,
		Illusion: 25,
		"Light Armor": 15,
		Lockpicking: 15,
		"One-Handed": 15,
		Pickpocket: 15,
		Restoration: 20,
		Smithing: 15,
		Sneak: 15,
		Speech: 15,
		"Two-Handed": 15,
	},
	Imperial: {
		Alchemy: 15,
		Alteration: 15,
		Archery: 15,
		Block: 20,
		Conjuration: 15,
		Destruction: 20,
		Enchanting: 20,
		"Heavy Armor": 20,
		Illusion: 15,
		"Light Armor": 15,
		Lockpicking: 15,
		"One-Handed": 20,
		Pickpocket: 15,
		Restoration: 25,
		Smithing: 15,
		Sneak: 15,
		Speech: 15,
		"Two-Handed": 15,
	},
	Khajiit: {
		Alchemy: 20,
		Alteration: 15,
		Archery: 20,
		Block: 15,
		Conjuration: 15,
		Destruction: 15,
		Enchanting: 15,
		"Heavy Armor": 15,
		Illusion: 15,
		"Light Armor": 15,
		Lockpicking: 20,
		"One-Handed": 20,
		Pickpocket: 20,
		Restoration: 15,
		Smithing: 15,
		Sneak: 25,
		Speech: 15,
		"Two-Handed": 15,
	},
	Nord: {
		Alchemy: 15,
		Alteration: 15,
		Archery: 15,
		Block: 20,
		Conjuration: 15,
		Destruction: 15,
		Enchanting: 15,
		"Heavy Armor": 15,
		Illusion: 15,
		"Light Armor": 20,
		Lockpicking: 15,
		"One-Handed": 20,
		Pickpocket: 15,
		Restoration: 15,
		Smithing: 20,
		Sneak: 15,
		Speech: 20,
		"Two-Handed": 25,
	},
	Orc: {
		Alchemy: 15,
		Alteration: 15,
		Archery: 15,
		Block: 20,
		Conjuration: 15,
		Destruction: 15,
		Enchanting: 20,
		"Heavy Armor": 25,
		Illusion: 15,
		"Light Armor": 15,
		Lockpicking: 15,
		"One-Handed": 20,
		Pickpocket: 15,
		Restoration: 15,
		Smithing: 20,
		Sneak: 15,
		Speech: 15,
		"Two-Handed": 20,
	},
	Redguard: {
		Alchemy: 15,
		Alteration: 20,
		Archery: 20,
		Block: 20,
		Conjuration: 15,
		Destruction: 20,
		Enchanting: 15,
		"Heavy Armor": 15,
		Illusion: 15,
		"Light Armor": 15,
		Lockpicking: 15,
		"One-Handed": 25,
		Pickpocket: 15,
		Restoration: 15,
		Smithing: 20,
		Sneak: 15,
		Speech: 15,
		"Two-Handed": 15,
	},
	"Wood Elf": {
		Alchemy: 20,
		Alteration: 15,
		Archery: 25,
		Block: 15,
		Conjuration: 15,
		Destruction: 15,
		Enchanting: 15,
		"Heavy Armor": 15,
		Illusion: 15,
		"Light Armor": 20,
		Lockpicking: 20,
		"One-Handed": 15,
		Pickpocket: 20,
		Restoration: 15,
		Smithing: 15,
		Sneak: 20,
		Speech: 15,
		"Two-Handed": 15,
	},
};